config/routes.rb
Rails.application.routes.draw do

  get '/recipes/search', to: 'recipes#search', as: 'recipes_search'

  resources :recipes

  resources :categories 

  resources :user do
      resources :recipes
    end

    resources :user do
      resources :categories
    end

  root to: 'application#welcome'

  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks'}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :recipes
    has_many :users, through: :recipes

    validates :name, :presence => true, :uniqueness => true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :user
    belongs_to :category
    
    accepts_nested_attributes_for :category, reject_if: :all_blank

    validates :title, presence:true
    validates :description, presence:true
    validates :directions, presence:true
    validates :ingredients, presence:true
    validates :title, uniqueness: true
    
    scope :look_up, ->(value) { where("title LIKE ?", "%#{value}%") }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :recipes
  has_many :categories, through: :recipes

  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.username = auth.info.name
      user.uid = auth.uid 
      user.email = auth.info.email 
      user.password = Devise.friendly_token[0,20]
    end 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def welcome        
    end 

    add_flash_types :success, :info, :danger        
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController 

    def github
        @user=User.from_omniauth(request.env["omniauth.auth"])
        # binding.pry
        sign_in_and_redirect @user
    end 

end 

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

    def index
        @categories = Category.all.order(:name)
    end 

    def show 
        @category = Category.find(params[:id]) 
    end 
end

app/controllers/recipe_controller.rb
class RecipeController < ApplicationController
    before_action :set_recipe, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!

    def index 
        @recipe = Recipe.all 
    end 

    def show
    end 

    def new 
        @recipe = Recipe.new
    end 

    def edit 
    end 

    def create 
        @recipe = Recipe.new(recipe_params)
    end 

    def update 
    end 

    def destroy 
        @recipe.destroy
    end 

    private 

    def set_recipe
        @recipe = Recipe.find(params[:id])
    end 

    def recipe_params
        params.require(:recipe).permit(:user_id, :title, :description)
    end 

end 

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :authenticate_user!

    def search 
        render :search 
    end 
    
    def index        
        @recipes = current_user.recipes
        if params[:search]
            @recipes = current_user.recipes.look_up(params[:search])
        else
            @recipes = current_user.recipes
        end
    end 

    def show
        @recipe = Recipe.find(params[:id]) 
    end

    def new 
        @recipe = current_user.recipes.build
    end 

    def edit 
        @recipe = current_user.recipes.find(params[:id])
    end

    def create
        @recipe = current_user.recipes.build(recipe_params)
        if @recipe.save
            redirect_to @recipe
            flash[:success] =  "You have successfully created a new recipe."
		else
			render :new
		end
    end 

    def update 
        @recipe = current_user.recipes.find(params[:id])
        if @recipe.update(recipe_params)
            redirect_to @recipe
            flash[:success] = "You have successfully updated the recipe."
        else
           render :edit
        end
    end

    def destroy 
        @recipe = Recipe.find(params[:id])
        @recipe.delete
        flash[:danger] = "You have successfully deleted the recipe."
        redirect_to recipes_path
    end 

    private 

    def find_recipe
        @recipe = Recipe.find(params[:id])
    end 

    def recipe_params
        params.require(:recipe).permit(:user_id, :title, :description, :directions, :ingredients, :category_id, category_attributes: [:name])
    end 
end

app/controllers/registerations_controller.rb
class RegisterationsController < ApplicationController

    private

    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private

    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/registerations_helper.rb
module RegisterationsHelper
end

app/views/application/welcome.html.erb
<br>
<h1> Welcome to a DashOfDelish!</h1>
<h4> Cooking is one of the greatest gift you can give to those you love</h4>
<h5> Just remember, the secret ingredient is love!</h5>


<div class="photo">
    <img src="https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="pancakes">
    <img src="https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" atl="burger">
    <img src="https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" atl="wrap">
    <img src="https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500"atl="fries">
    <img src="https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" atl="cake">
    <img src="https://images.pexels.com/photos/704569/pexels-photo-704569.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" atl="eggs">
    <img src="https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" atl="fish">
    <img src="https://images.pexels.com/photos/949069/pexels-photo-949069.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" atl="oatmeal">
    <img src="https://images.pexels.com/photos/1132558/pexels-photo-1132558.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940" atl="pafait" >
</div>

app/views/categories/index.html.erb
 <h2> All Categories </h2>

<br>

<h6>
    <% @categories.each do |category| %><br>
        <%= link_to category.name, category_path(category) %><br>
    <% end %>  
</h6>

app/views/categories/show.html.erb
<h1><%= @category.name%></h1>

<h6>
    <% @category.recipes.each do |r| %><br>
        <%=  r.title.capitalize %><br>
    <% end %>
</h6>
 

app/views/layouts/_nav.html.erb
<nav> 
    <ul>
        <%= link_to "Home", root_path %><br>
        <% if !user_signed_in? %>
            <%= link_to "Signup", new_user_registration_path %><br>
            <%= link_to "Login", new_user_session_path %><br>
        <% else %>
            <%= current_user.email %><br>
            <%= link_to "My Recipes", user_recipes_path(current_user) %><br>
            <%= link_to "Categories", user_categories_path(current_user) %><br>
            <%= link_to "Logout", destroy_user_session_path, method:"delete" %><br>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DashOfDelish</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>

    .photo {
        text-align: center;
        padding: 10px;
        margin: 4px 0 0 4px;
        box-shadow: 0 0 0 4px #fff;
    }
    .photo img {
      width: 300px; 
      height: 215px;
      background-size: cover;
      object-fit: cover;
    }

    h2, h4, h1, h5 {
      text-align: center;
    }

    body {
      padding: 30px;
      font-family: Didot;
    }

    .navigation a {
      color: teal;
    }
        
  </style>

  <body>

  <div class="container">

    <ul class="navigation">
      <%= render 'layouts/nav' %>
    <ul>

    <%flash.each do |name, msg| %> 
      <div class='alert alert-<%= name %>'>
      <%= msg %>
    </div>
    <% end %>

     <%= yield %>
  </div>


  </body>
</html>

app/views/recipes/_form.html.erb
 <% if @recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
        <% @recipe.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_for @recipe do |f|%>

    <div>
        <%= f.label "Title:" %> 
        <%= f.text_field :title, :class => 'form-control'  %>
    </div>

    <div>
        <%= f.label "Description:" %> 
        <%= f.text_area :description, :class => 'form-control'  %>
    </div>

    <% if params[:category_id].blank? %>
        <div>
            <p>Select a category that already exists: </p>
            <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %> 
        </div>
            <p> Or create a new category: </p>

        <div>
            <%= f.fields_for :category, @recipe.build_category do |category_field|%>
            <%= category_field.text_field :name, :class => 'form-control'  %>
            <% end %>
        </div>
        <% else %>
        <%= hidden_field_tag "recipe[category_id]", params[:category_id] %>
    <% end %>


    <div>
        <%= f.label "Ingredients:" %><br>
        <%= f.text_area :ingredients, :class => 'form-control'  %>
    </div>

    <div>
        <%= f.label "Directions:" %><br>
        <%= f.text_area :directions, :class => 'form-control'  %>
    </div>
    <br>


    <%= f.submit button_label %>

<% end %>


 



 

app/views/recipes/edit.html.erb
<h2>Edit Recipe</h2>

<%= render partial: "form", locals: {recipe: @recipe, button_label: "Update Recipe"} %>
<br>


<%= link_to "Home", recipes_path %>
<br>
<%= link_to "Recipes", recipes_path %>

app/views/recipes/index.html.erb
<div>
    <h1>Recipes</h1>
    <br>
    <% @recipes.each do |recipe| %>
    <h6><%= link_to recipe.title, recipe %></h6>
    <% end %>
        
    <br>
    <br>
    <p> Looking for a Particular Recipe? <%= link_to "Search", recipes_search_path %></p>

    <br>
    <br>
    
    <%= link_to "Create a New Recipe", new_user_recipe_path(current_user) %></p>

</div>

app/views/recipes/new.html.erb
<br>
<br>

<h1>Create a New Recipe: </h1>

<br> 
<%= render partial: "form", locals: {recipe: @recipe, button_label: "Create New Recipe"} %>

app/views/recipes/search.html.erb
   
   <br>
   <br>
   
    <p> Looking for a Particular Recipe? </p>

    <%= form_tag recipes_path, :method => 'get' do %>   
        <%= text_field_tag :search, params[:search] %>   
        <%= submit_tag "Search" %> 
    <% end %>

app/views/recipes/show.html.erb
<br>

<h1><%= @recipe.title %></h1>

<br>

<p><strong> Description: </strong> <%= @recipe.description %></p>

<p><strong> Category: </strong> <%= @recipe.category.name %></p>

<p><strong> Ingredients: </strong> <%= @recipe.ingredients %></p>

<p><strong> Directions: </strong> <%= @recipe.directions %><p></p>

<%= button_to "delete", @recipe, :method => :delete %>
<br>
<%= link_to "Edit Recipe", edit_recipe_path %> | <%= link_to "New Recipe", new_user_recipe_path(current_user) %></p>